name: "Pinata Security Scan"
description: "Scan your codebase for security vulnerabilities and test coverage gaps"
author: "Pinata Security"

branding:
  icon: "shield"
  color: "red"

inputs:
  path:
    description: "Path to scan (default: current directory)"
    required: false
    default: "."
  confidence:
    description: "Minimum confidence level: high, medium, low"
    required: false
    default: "high"
  domains:
    description: "Comma-separated domains to scan (e.g. security,data)"
    required: false
    default: ""
  verify:
    description: "Use AI verification to reduce false positives"
    required: false
    default: "false"
  anthropic-api-key:
    description: "Anthropic API key (required if verify is true)"
    required: false
  fail-on-gaps:
    description: "Fail the action if gaps are found"
    required: false
    default: "true"
  sarif-output:
    description: "Path to write SARIF output file"
    required: false
    default: ""

outputs:
  score:
    description: "Pinata score (0-100)"
    value: ${{ steps.scan.outputs.score }}
  gaps:
    description: "Number of gaps found"
    value: ${{ steps.scan.outputs.gaps }}
  sarif-file:
    description: "Path to SARIF file if generated"
    value: ${{ steps.scan.outputs.sarif }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install Pinata
      shell: bash
      run: npm install -g pinata-security-cli@latest

    - name: Run Pinata Scan
      id: scan
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
      run: |
        set +e  # Don't exit on error
        
        # Build base command
        CMD="pinata analyze ${{ inputs.path }} --confidence ${{ inputs.confidence }}"
        
        # Add domains if specified
        if [ -n "${{ inputs.domains }}" ]; then
          CMD="$CMD --domains ${{ inputs.domains }}"
        fi
        
        # Add verify if enabled
        if [ "${{ inputs.verify }}" = "true" ]; then
          CMD="$CMD --verify"
        fi
        
        # Run scan with JSON output
        echo "Running: $CMD --output json"
        JSON_OUTPUT=$($CMD --output json 2>&1)
        
        # Parse results using jq
        SCORE=$(echo "$JSON_OUTPUT" | jq -r '.score.overall // 0')
        GAPS=$(echo "$JSON_OUTPUT" | jq -r '.gaps | length // 0')
        GRADE=$(echo "$JSON_OUTPUT" | jq -r '.score.grade // "?"')
        
        echo "score=$SCORE" >> $GITHUB_OUTPUT
        echo "gaps=$GAPS" >> $GITHUB_OUTPUT
        
        # Generate SARIF if requested
        SARIF_PATH="${{ inputs.sarif-output }}"
        if [ -n "$SARIF_PATH" ]; then
          $CMD --output sarif --output-file "$SARIF_PATH" 2>/dev/null || true
          echo "sarif=$SARIF_PATH" >> $GITHUB_OUTPUT
        fi
        
        # Display summary
        echo "### Pinata Security Scan" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Score:** $SCORE/100 ($GRADE)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Gaps Found:** $GAPS" >> $GITHUB_STEP_SUMMARY
        
        # List top 5 gaps if any
        if [ "$GAPS" -gt 0 ]; then
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "#### Top Gaps" >> $GITHUB_STEP_SUMMARY
          echo "$JSON_OUTPUT" | jq -r '.gaps[:5][] | "- **\(.category)** (\(.severity)): \(.description) at `\(.filePath):\(.lineStart)`"' >> $GITHUB_STEP_SUMMARY
        fi
        
        # Fail if gaps found and fail-on-gaps is true
        if [ "${{ inputs.fail-on-gaps }}" = "true" ] && [ "$GAPS" -gt 0 ]; then
          echo "::error::Pinata found $GAPS security gaps"
          exit 1
        fi

    - name: Upload SARIF to GitHub Security
      if: inputs.sarif-output != ''
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.sarif-output }}
